[2025-01-28T23:33:10.399+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T23:33:10.416+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pull_gazettes_data.download_contents_version_from_s3_task scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-01-28T23:33:10.425+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pull_gazettes_data.download_contents_version_from_s3_task scheduled__2025-01-27T00:00:00+00:00 [queued]>
[2025-01-28T23:33:10.426+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-01-28T23:33:10.440+0000] {taskinstance.py:2888} INFO - Executing <Task(DownloadContentFromS3): download_contents_version_from_s3_task> on 2025-01-27 00:00:00+00:00
[2025-01-28T23:33:10.449+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2502) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T23:33:10.450+0000] {standard_task_runner.py:72} INFO - Started process 2504 to run task
[2025-01-28T23:33:10.450+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pull_gazettes_data', 'download_contents_version_from_s3_task', 'scheduled__2025-01-27T00:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmp38707vwc']
[2025-01-28T23:33:10.452+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask download_contents_version_from_s3_task
[2025-01-28T23:33:10.496+0000] {task_command.py:467} INFO - Running <TaskInstance: pull_gazettes_data.download_contents_version_from_s3_task scheduled__2025-01-27T00:00:00+00:00 [running]> on host 41bcec3d818b
[2025-01-28T23:33:10.584+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pull_gazettes_data' AIRFLOW_CTX_TASK_ID='download_contents_version_from_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T00:00:00+00:00'
[2025-01-28T23:33:10.585+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T23:33:10.608+0000] {base.py:84} INFO - Retrieving connection 'minio_s3_conn_id'
[2025-01-28T23:33:10.609+0000] {connection_wrapper.py:391} INFO - AWS Connection (conn_id='minio_s3_conn_id', conn_type='aws') credentials retrieved from extra.
[2025-01-28T23:33:10.610+0000] {warnings.py:112} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2025-01-28T23:33:11.403+0000] {logging_mixin.py:190} INFO - Key vector_db/index.faiss does not exists in bucket diario-oficial-db-dump
[2025-01-28T23:33:11.411+0000] {logging_mixin.py:190} INFO - Key vector_db/index.pkl does not exists in bucket diario-oficial-db-dump
[2025-01-28T23:33:11.419+0000] {logging_mixin.py:190} INFO - Key ingestion_checkpoint_logs/collection.json does not exists in bucket diario-oficial-db-dump
[2025-01-28T23:33:11.426+0000] {logging_mixin.py:190} INFO - Key ingestion_checkpoint_logs/log_urls.csv does not exists in bucket diario-oficial-db-dump
[2025-01-28T23:33:11.433+0000] {logging_mixin.py:190} INFO - Key ingestion_checkpoint_logs/preprocessed_documents_log.csv does not exists in bucket diario-oficial-db-dump
[2025-01-28T23:33:11.443+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T23:33:11.444+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pull_gazettes_data, task_id=download_contents_version_from_s3_task, run_id=scheduled__2025-01-27T00:00:00+00:00, execution_date=20250127T000000, start_date=20250128T233310, end_date=20250128T233311
[2025-01-28T23:33:11.508+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T23:33:11.533+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-28T23:33:11.536+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
